from typing import List, TypedDict, Annotated
from langgraph.graph.message import add_messages


class ResearchState(TypedDict):
    """
    Represents the state of our multi-agent graph.
    
    Attributes:
        query: The user's original query.
        research_data: A list of research findings.
        development_plan: The high-level plan for the project.
        code_draft: The Python script generated by the coder.
        final_report: The final, compiled report.
        next: A string used for routing the graph to the next node.
        messages: A history of messages between agents and the user.
    """
    query: str
    rag_context: str  # Add this new field
    research_data: Annotated[List[str], lambda x, y: x + y]
    development_plan: str
    code_draft: str
    final_report: str
    next: str
    messages: Annotated[List[str], lambda x, y: x + y]